### ISSUE TITLE
mcopy from grub-mkrescue fails

### ISSUE THREAD

**Issue by DevManu-de** [TinyKern/TinyKernel#7]
The latest updated solved the linking issue but `mcopy` from `grub-mkrescue` now fails.
```
CC src/sys/char.c -> build/obj/src/sys/char.c.o
CC src/sys/utils.c -> build/obj/src/sys/utils.c.o
CC src/drivers/keyboard/keyboard.c -> build/obj/src/drivers/keyboard/keyboard.c.o
CC src/drivers/vga/vga.c -> build/obj/src/drivers/vga/vga.c.o
AS src/bootloader/boot.s -> build/obj/src/bootloader/boot.s.o
CC src/kernel/stdio.c -> build/obj/src/kernel/stdio.c.o
src/kernel/stdio.c: In function ‘__kprintf’:
src/kernel/stdio.c:60:15: warning: comparison of unsigned expression in ‘< 0’ is always false [-Wtype-limits]
   60 |         if (i < 0)
      |               ^
CC src/kernel/cpu/ports.c -> build/obj/src/kernel/cpu/ports.c.o
CC src/kernel/kernel.c -> build/obj/src/kernel/kernel.c.o
CC src/kernel/errno.c -> build/obj/src/kernel/errno.c.o
\nLinking -> build/boot/TinyKernel.bin
mcopy: No directory slots
grub-mkrescue: error: `mcopy` invocation failed
.
make: *** [Makefile:52: iso] Error 1

```

_Originally posted by @DevManu-de in https://github.com/TinyKern/TinyKernel/issues/6#issuecomment-884188006_

**Comment by bobrossrtx** [comment]
Hey @DevManu-de I haven't been working on this issue for past few days because I'm on holiday, but I will make this a priority for when I get home later today. If you can find the fix to the issue, feel free to share, or even make a pull request.

**Comment by bobrossrtx** [comment]
It seems that the problem is that the mtools version you have installed is either out of date, or has a bug. I know for sure now that version `4.0.32` & `4.0.33` have bugs with mcopy and this is the exact issue it causes. I recommend updating to `4.0.34` or below `4.0.32`, other than that, that should solve the issue.

**Comment by bobrossrtx** [comment]
If you would like to update to the latest version, here is the link to the official GNU mirror, https://www.gnu.org/software/mtools

**Comment by DevManu-de** [comment]
It works now, i think the problem was with an outdated mcopy version.
Sorry for that inconvenience.

**Comment by bobrossrtx** [comment]
It is all good, we all have problems like this :p
